- name: Install git
  become: true
  when: ansible_distribution == 'Ubuntu'
  ansible.builtin.apt:
    name: git
    state: present

- name: Install git
  become: true
  when: ansible_distribution == 'Fedora'
  ansible.builtin.dnf:
    name: git
    state: present

- name: Copy gitconfig
  ansible.builtin.copy:
    src: .gitconfig
    dest: "{{ lookup('ansible.builtin.env', 'HOME') }}/.gitconfig"
    owner: "{{ lookup('ansible.builtin.env', 'USER') }}"
    mode: "0644"
